---
abstract: 'Extracts XML into Perl Datasets based upon a simple text profile markup language'
author:
  - 'James Spurin <james@spurin.com>'
build_requires:
  Data::Printer: '0'
  Test::More: '0'
  Test::Warn: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: XML-Dataset
requires:
  Data::Alias: '0'
  Data::Dumper: '0'
  XML::LibXML::Reader: '0'
  strict: '0'
  warnings: '0'
version: '0.001'
